name: skripsi_streamlit
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit>=1.33
      - pandas>=2.0
      - numpy>=1.24
      - scikit-learn>=1.3
      - prefixspan>=0.5.2
